# Generated by Django 4.1.5 on 2023-01-22 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.TextField(default=datetime.datetime(2023, 1, 22, 1, 50, 35, 357749, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
